config/routes.rb
Publication::Application.routes.draw do

  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? && request.env['warden'].user.is_admin? }
  constraints constraint do
    mount Sidekiq::Web => '/queue'
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {registrations: :registrations}

  match 'opensearch' => 'items#opensearch', :as => :opensearch
  match 'benchmark_solr' => 'items#benchmark_solr', :as => :benchmark_solr
  match 'search' => 'items#search', :as => :search
  match 'feed' => "items#feed", :as => :feed
  match 'languages/:language_id/items/page/:page' => 'items#index'
  match 'categories/:category_id/:page' => 'items#index'

  match 'news/:category/:id' => 'items#show', :as => :news_path

  post '/tinymce_assets' => 'attachments#create'

  # Omniauth
  match '/auth/:provider/callback', to: 'services#create'
  match '/auth/failure' => 'services#failure'
  resources :services, :only => [:create, :destroy]

  namespace "api" do
    resources :git_push
  end

  # opinio_model
  resources :authors do
    resources :items
    resources :comments, controller: 'opinio/comments'
  end

  resources :items do
    resources :language
    resources :category
    opinio
    get 'vote'
  end

  resources :comments, controller: 'opinio/comments' do
    get 'reply', on: :member
    get 'vote'
  end

  resources :links, only: [:index]
  resources :subscriptions, only: [:index, :destroy]
  resources :contacts
  resources :pages
  resources :roles
  resources :tags
  resources :general_tags
  resources :region_tags
  resources :country_tags
  resources :categories
  resources :attachments
  resources :scores
  resources :translations
  resources :languages do
    resources :items
  end

  # Main Items feed
  match '/atom' => 'items#index', :as => :items_atom, :defaults => { :format => 'atom' }
  match '/rss'  => 'items#index', :as => :items_rss,  :defaults => { :format => 'rss' }


  namespace :tasks do
    get 'sitemap'
  end

  root to: 'categories#index'

  match '*not_found', to: 'errors#error_404'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :user
  belongs_to :attachable, polymorphic: true, touch: true
  belongs_to :existing_attachment, foreign_key: 'parent_id', class_name: "Attachment", touch: true
  mount_uploader :image, ImageUploader
  has_paper_trail :on => [:edit, :destroy]

  def alt_text
    if title.present?
      title.to_s
    else
      "image"
    end
  end
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController

  def create
    authorize! :create, Attachment
    # Take upload from params[:file] and store it somehow...
    # Optionally also accept params[:hint] and consume if needed
    @attachment = Attachment.new
    @attachment.image = params[:file] if params[:file]
    if @attachment.valid? && @attachment.save
      render json: {
        image: {
          url: @attachment.image.large.url
        }
      }, content_type: "text/html"
    end
  end

end

app/views/admin/attachments/_attachment.html.erb
<% cache_expiring("aip/#{attachment.cache_key}", 1.day) do %>
<%=
  if attachment.existing_attachment
    link_to(
      image_tag(attachment.existing_attachment.image.medium.url, alt: attachment.title),
      admin_attachment_path(attachment),
      title: attachment.title,
    )
  elsif attachment.image.present?
    link_to(
      image_tag(attachment.image.medium.url, alt: attachment.title),
      admin_attachment_path(attachment),
      title: attachment.title,
    )
  else
    link_to(
      "No Image Uploaded",
      admin_attachment_path(attachment),
      title: attachment.title,
    )
  end
%>

<p><%= auto_link(attachment.attachable) %></p>
<p><%= attachment.title %></p>
<p>
  <%= link_to("Copy", "#", id: "button-copy-#{attachment.id}", class: "button") %>
  <%= link_to("Edit", edit_admin_attachment_path(attachment), title: "Edit Image", class: "button") %>
  <%= link_to("Delete", admin_attachment_path(attachment), method: "delete",
          confirm: "Really delete this image?",
          title: "Click on image to see details",
          class: "button"
      )
  %>
</p>

<div class="hidden" id="copy-<%=attachment.id%>">
<p>
<%=
  if attachment.existing_attachment
    link_to(
      image_tag(attachment.existing_attachment.image.full.url, title: attachment.title, alt: attachment.alt_text),
      attachment.image.url,
      title: attachment.title,
      targe: "_blank",
      class: "image-popup"
    )
  elsif attachment.image.present?
    link_to(
      image_tag(attachment.image.full.url, title: attachment.title, alt: attachment.alt_text),
      attachment.image.url,
      title: attachment.title,
      targe: "_blank",
      class: "image-popup"
    )
  end
%>
<% if attachment.title.present? %>
<br />
<span class="image-caption"><%= attachment.title.to_s.truncate(100) %></span>
<% end %>
</p>
</div>

<script type="text/javascript">
  // $("a#button-copy-<%= attachment.id %>").zclip({
  //   path:'/assets/ZeroClipboard10.swf',
  //   copy:$('div#copy-<%= attachment.id %>').html()
  // });

  $("a#button-copy-<%= attachment.id %>").click(function () {
    var txt = "Copy the following text to paste in HTML mode:\n" + $('div#copy-<%= attachment.id %>').html();
    alert(txt);
  });

</script>

<% end %>

app/views/admin/attachments/_form.html.erb
<%= semantic_form_for [:admin, @attachment], html: { enctype: "multipart/form-data" }  do |f| %>
  <%= f.inputs name: "Required Information" do %>
    <%= f.input :title, label: "Image caption" %>
    <%= f.input :image, as: "file",
                        input_html: {multiple: @attachment.new_record?},
                        label: "Choose image to upload",
                        hint: "When editing, the new image will overwrite the old image. Multiple images are allowed, you can select multiple images holding CTRL or Command keys when choosing images." %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit, button_html: {class: "primary", data: {disable_with: 'Uploading...'}} %>
  <% end %>
<% end %>


<script type="text/javascript">
  $("#attachment_title").counter({
      count: 'up',
      goal: 160
  });
  $("form#new_attachment").validate({
    rules: {
      "attachment[image]": { required: true }
    }
  });
</script>

app/views/admin/attachments/_show.html.erb
<% if @attachment.existing_attachment %>
  <% @attachment = @attachment.existing_attachment %>
<% end %>

<div class="panel">
  <h3>Image Details</h3>
  <div class="panel_contents">
    <div class="attributes_table image">
      <p>Image Caption: <b><%= @attachment.title %></b></p>
      <% if @attachment.attachable && @attachment.attachable.user %>
        <p>Uploaded by: <b><%= link_to(@attachment.attachable.user.email, admin_user_path(@attachment.attachable.user)) %></b></p>
      <% end %>
      <p>Created at: <b><%= @attachment.created_at.to_s(:long) %></b></p>
    </div>
  </div>
</div>

<div class="panel">
  <h3>Images</h3>
  <div class="panel_contents">
    <div class="attributes_table images">
      <% if @attachment.image.present? %>
        <% @attachment.image.versions.each do |t| %>
          <%= image_tag(t[1], class: "show_listing_img") %>
          <br />
          <h4><%= t[0] %>: <%= link_to "#{t[1]}", @attachment.image.url(t[0].to_sym), target: "blank" %></h4>
          <br />
          <hr />
        <% end %>
        <%= image_tag(@attachment.image.url, class: "show_listing_img")  %>
        <h4>Original Image: <%= link_to @attachment.image.url, @attachment.image.url, target: "blank" %></h4>
      <% else %>
        No Image Uploaded
      <% end %>
    </div>
  </div>
</div>

app/views/admin/attachments/_show_attachment_list.html.erb
<% unless @attachments.empty? %>
<ul class="attachment_list">
<% @attachments.each do |p| %>
<li id="<%= p.id %>" class="attachment_list">
   <%if params[ :media ] == 'print'%> 
  <div class="thumbs">
    Insert:
        <br/>
        <%= link_to "Fullscreen", p.image.url( :full ), onclick: "select_thumb(this);return false;"%>
        <br/>
        <%= link_to "Large", p.image.url( :large ), onclick: "select_thumb(this);return false;"%>
        <br/>
        <%= link_to "Main", p.image.url( :medium_thumb ), onclick: "select_thumb(this);return false;"%>
        <br/>
        <%= link_to "Medium", p.image.url( :small_thumb ), onclick: "select_thumb(this);return false;"%>
        <br/>
        <%= link_to "Small", p.image.url( :small_thumb ), onclick: "select_thumb(this);return false;"%>
        <br/>
        <%= link_to "Thumb", p.image.url( :small_thumb ), onclick: "select_thumb(this);return false;"%>
        <br/>
        <%= link_to 'Cancel', 'javascript:void(0)', onclick: "cancel_image();return false;"%>
    </div>
      <%= link_to_function( image_tag( p.image.url( :small_thumb ), alt: p.image.name ), "select_image(this)" )%>
    <% else%>
      <%= link_to p.original_file_name, p.original.url, onclick: "select_thumb(this);return false;"%>&nbsp;&nbsp;&nbsp;
    <% end%>
</li>
<% end %>
</ul>
<br style="clear:both;" />
<div style="float:right;margin-bottom:10px;">
  <%= will_paginate @attachments, class: "pagination", 
        previous_label: "&laquo; previous",
        next_label: "next &raquo;",
        renderer: 'RemoteLinkRenderer'
  %>
</div>
<% else %>
  No <%= params[ :media ]%> Uploaded Yet.
<% end %>