config/routes.rb
Publication::Application.routes.draw do

  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? && request.env['warden'].user.is_admin? }
  constraints constraint do
    mount Sidekiq::Web => '/queue'
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {registrations: :registrations}

  match 'opensearch' => 'items#opensearch', :as => :opensearch
  match 'benchmark_solr' => 'items#benchmark_solr', :as => :benchmark_solr
  match 'search' => 'items#search', :as => :search
  match 'feed' => "items#feed", :as => :feed
  match 'languages/:language_id/items/page/:page' => 'items#index'
  match 'categories/:category_id/:page' => 'items#index'

  match 'news/:category/:id' => 'items#show', :as => :news_path

  post '/tinymce_assets' => 'attachments#create'

  # Omniauth
  match '/auth/:provider/callback', to: 'services#create'
  match '/auth/failure' => 'services#failure'
  resources :services, :only => [:create, :destroy]

  namespace "api" do
    resources :git_push
  end

  # opinio_model
  resources :authors do
    resources :items
    resources :comments, controller: 'opinio/comments'
  end

  resources :items do
    resources :language
    resources :category
    opinio
    get 'vote'
  end

  resources :comments, controller: 'opinio/comments' do
    get 'reply', on: :member
    get 'vote'
  end

  resources :links, only: [:index]
  resources :subscriptions, only: [:index, :destroy]
  resources :contacts
  resources :pages
  resources :roles
  resources :tags
  resources :general_tags
  resources :region_tags
  resources :country_tags
  resources :categories
  resources :attachments
  resources :scores
  resources :translations
  resources :languages do
    resources :items
  end

  # Main Items feed
  match '/atom' => 'items#index', :as => :items_atom, :defaults => { :format => 'atom' }
  match '/rss'  => 'items#index', :as => :items_rss,  :defaults => { :format => 'rss' }


  namespace :tasks do
    get 'sitemap'
  end

  root to: 'categories#index'

  match '*not_found', to: 'errors#error_404'
end

app/helpers/layout_helper.rb
module LayoutHelper

  def logged_in?
    (current_user or current_admin_user)
  end

  def link_to_google_auth
    link_to("Login with Gmail",
      "https://#{Settings.host}/auth/google_oauth2",
      class: "zocial google",
      rel: 'nofollow',
      title: "Login with Gmail"
    )
  end

  def link_to_twitter_auth
    link_to("Login with Twitter",
      "/auth/twitter",
      class: "zocial twitter",
      rel: 'nofollow',
      title: "Login with Twitter"
    )
  end

  def link_to_windowslive_auth
    link_to("Login Windows Live",
      "/auth/windowslive",
      class: "zocial windows",
      rel: 'nofollow',
      title: "Login Windows Live"
    )
  end

  def link_to_facebook_auth
    link_to("Login with Facebook",
      "/auth/facebook",
      class: "zocial facebook",
      rel: 'nofollow',
      title: "Login with Facebook"
    )
  end

  def canonical_item_link_tag(item)
    tag(:link,
      rel: 'canonical',
      href: url_for(
        item_path(item,
          only_path: false,
          protocol: 'http',
          host: localized_host(item.language_title_short)
        )
      )
    ).html_safe
  end

  def localized_host(lang)
    if request.domain
      if lang.match(Item::DEFAULT_LOCALE)
        "#{request.domain}"
      else
        "#{lang}.#{request.domain}"
      end
    else
      Settings.host
    end
  end

  def localized_subdomain(lang)
    if request.domain
      "http://#{lang}.#{request.domain}"
    else
      "http://#{Settings.host}"
    end
  end

  def host_link
    "http://#{Settings.host}"
  end

  def flattr_link
    Settings.flattr_link
  end

  def facebook_link
    Settings.facebook_link
  end

  def twitter_link
    Settings.twitter_link
  end

  def google_plus_link
    Settings.google_plus_link
  end

  def twitter_user_link(str)
    if str.match(/^https?:\/\//)
      link_to "@#{str.split("/").last}", str
    else
      link_to "@#{str.gsub('@','')}", "https://twitter.com/#{str.gsub('@','')}"
    end
  end

  def twitter_username(str)
    if str.match(/^https?:\/\//)
      str.split("/").last
    else
      str.gsub('@','')
    end
  end

  def rss_medium
    link_to(
      image_tag("icons/social/new/rss_32b.png", width: 32, height: 32, alt: 'rss'),
      feed_path,
      title: "Multiple RSS Feeds"
    )
  end

  def facebook_medium
    link_to(
      image_tag("icons/social/new/facebook_32b.png", width: 32, height: 32, alt: 'Facebook'),
      facebook_link,
      title: "Facebook"
    )
  end

  def twitter_medium
    link_to(
      image_tag("icons/social/new/twitter_32.png", width: 32, height: 32, alt: 'Twitter'),
      twitter_link,
      title: "Twitter"
    )
  end

  def google_plus_medium
    link_to(
      image_tag("icons/social/google_plus_32.png", width: 32, height: 32, alt: 'Google+'),
      google_plus_link,
      title: "Google+",
      rel: "me"
    )
  end

  def google_plus_new
    link_to(
      image_tag("icons/social/new/gplus_32b.png", width: 32, height: 32, alt: 'Google+', class: "google-plus"),
      google_plus_link,
      title: "Google+",
      rel: "me",
      class: "google-plus"
    )
  end
  
  def flattr_large
    link_to(
      image_tag("flattr-badge-large.png", width: 93, height: 20, alt: "Flattr",),
      flattr_link,
      target: "blank",
      title: "Flattr This Site",
      class: 'flattr-large'
    )
  end
  
  def flattr_medium
    link_to(
      image_tag("flattr-badge-medium.png", width: 32, height: 32, alt: "Flattr"),
      flattr_link,
      target: "blank",
      title: "Flattr This Site",
      class: 'flattr-medium'
    )
  end
  
  def flattr_js
    "<a class='FlattrButton' style='display:none;' rev='flattr;button:compact;' href='#{host_link}'></a>
    <noscript>
      <a href='#{flattr_link}' target='_blank'>
        <img src='/assets/flattr-badge-large.png' alt='Flattr this' title='Flattr this' border='0' />
      </a>
    </noscript>"
  end

  def mobile_css(mobile_class='span6',desktop_class='span8')
    if is_mobile?
      mobile_class
    else
      desktop_class
    end
  end

  def form_class(with_class="")
    if is_mobile?
      str = "form-vertical"
    else
      str = "form-horizontal"
    end
    "#{str} #{with_class}"
  end

  def li_class_subdomain(str, css_class="active")
    if request.subdomains.first && request.subdomains.first.to_s.match(str)
      css_class
    else
      ""
    end
  end

  def li_class(str, sym="id", css_class="active")
    if params[sym.to_sym].present? && (params[sym.to_sym].to_s == str.to_s)
      css_class
    else
      ""
    end
  end

  def login_link(str)
    if is_handheld?
      link_to str, new_session_url(:user, protocol: 'https'), title: "Login"
    else
      "<a data-toggle='modal' data-target='#modal-login' href='#' >#{str}</a>".html_safe
    end
  end

  def youtube_height(item)
    if is_mobile?
      item.youtube_mobile_height
    else
      item.youtube_height
    end
  end

  def youtube_width(item)
    if is_mobile?
      item.youtube_mobile_width
    else
      item.youtube_width
    end
  end

end

app/views/shared/layouts/_chrome_frame.html.erb
<!--[if lt IE 8]>
  <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.3/CFInstall.min.js"></script>
  <script>window.attachEvent('onload',function(){CFInstall.check({mode:'overlay'})})</script>
  <style>
    .chromeFrameInstallDefaultStyle {
      width: 800px;
      height: 500px;
      position: absolute;
      left: 50%;
      top: 50%;
      margin-left: -400px;
      margin-top: -260px;
    }
    .chromeFrameOverlayContent {
      position: absolute;
      margin-left: -400px;
      margin-top: -260px;
      left: 50%;
      top: 50%;
      border: 1px solid #93B4D9;
      background-color: white;
      z-index: 2001;
    }
    .chromeFrameOverlayContent iframe {
      width: 800px;
      height: 500px;
      border: none;
    }
    .chromeFrameOverlayCloseBar {
      height: 1em;
      text-align: right;
      background-color: #CADEF4;
    }
    .chromeFrameOverlayUnderlay {
      position: absolute;
      width: 100%;
      height: 100%;
      background-color: white;
      opacity: 0.5;
      -moz-opacity: 0.5;
      -webkit-opacity: 0.5;
      -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
      filter: alpha(opacity=50);
      z-index: 2000;
    }
  </style>
<![endif]-->

app/views/shared/layouts/_footer.html.erb
<footer>
  
  <% cache_expiring("footer/top", 1.day) do %>
    <ul class="footer_menu footer_categories">
      <% @site_categories.each do |category| %>
        <li>
          <%= link_to category.title, category, title:  category.description %>
        </li>
      <% end %>
    </ul>

    <ul class="footer_menu">
      <% @site_pages.each do |page| %>
        <li><%= link_to page.title, page, title: page.title %></li>
      <% end %>

      <li>
        <%= link_to _("Feeds"), feed_path, title: _("Multiple RSS Feeds") %>
      </li>
    </ul>
  <% end %>

  <ul class="footer_menu">
    <% if current_user or current_admin_user %>
      <li>
        <%= link_to _("Edit Profile"),
              edit_user_registration_url(protocol: http_protocol),
              title: _("Edit your Profile information")
        %>
      </li>
      <li>
        <%= link_to _('Logout'),
              destroy_user_session_url(protocol: http_protocol),
              method: :delete, title: _("Logout")
        %>
      </li>
    <% else %>
      <li>
        <%= login_link _('Login') %>
      </li>
      <%- if Devise.mappings[:user].registerable?  %>
        <li>
          <%= link_to _("Registration"),
                new_registration_url(:user, protocol: http_protocol),
                title: _("Please Join us")
          %>
        </li>
      <% end %>
      <%- if Devise.mappings[:user].recoverable? && controller_name != 'passwords' %>
        <li>
          <%= link_to _("Forgot password?"),
                new_password_url(:user, protocol: http_protocol), 
                title: _("Click here to recover your password.")
          %>
        </li>
      <% end %>
    <% end %>
  </ul>

  <p class="footer_logo">
    World Mathaba
  </p>
  <% if @start_time %>
  <p class="render_time">
    Page Rendered in <strong><%= sprintf('%.3f', (Time.now.usec - @start_time).abs / 1000000.0) %></strong> seconds
  </p>
  <% end %>
  <p class="render_time">
    <%= link_to 'Source code under GPLv3', "https://github.com/fred/mnn", title: 'License and Source Code', rel: 'license' %>
  </p>
</footer>

app/views/shared/layouts/_ga.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', "<%= Settings.google_analytics %>"]);
  _gaq.push(['_setDomainName', "<%= Settings.host %>"]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/shared/layouts/_head.html.erb
<meta charset="UTF-8">
<!--[if ie]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<meta name="application-name" content="World Mathaba Independent News Agency">
<meta name="generator" content="Ruby on Rails">
<base href="<%= url_for root_path(only_path: false, protocol: request.protocol) %>">
<% if @meta_description %>
<meta name="description" content="<%= @meta_description %>">
<% else %>
<meta name="description" content="World Mathaba Independent News Agency">
<% end %>
<% if @meta_keywords %>
<meta name="keywords" content="news, <%= @meta_keywords %>">
<% else %>
<meta name="keywords" content="worldmathaba, news, independent, alternative">
<% end %>
<% if @meta_author %>
<meta name="author" content="<%= @meta_author %>">
<% else %>
<meta name="author" content="World Mathaba Independent News Agency">
<% end %>
<% if @meta_title %>
<title> <%= @meta_title %> </title>
<link rel='index' title="<%= @meta_title %>" href="<%= url_for root_path %>" />
<% else %>
<title>World Mathaba Independent News</title>
<link rel='index' title="World Mathaba Independent News" href="<%= url_for(root_path(only_path: false, protocol: 'http'))%>" />
<% end %>
<meta name="viewport" content="width=device-width; maximum-scale=2.0; initial-scale=1.0; user-scalable=yes"/>
<meta name="HandheldFriendly" content="true"/>
<link rel="shortcut icon" type="image/png" href="/assets/favicon.ico" />

app/views/shared/layouts/_navbar.html.erb
<!-- Topbar
================================================== -->
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <% cache_expiring("navbar", 2.hours) do %>
        <%= link_to(image_tag("world_mathaba.png",
                    width: '200',
                    height: '33',
                    class: 'brand',
                    title: 'World Mathaba Independent News Agency',
                    alt: 'World Mathaba'
                  ),
              root_path,
              title: 'World Mathaba Independent News Agency',
              rel: 'home'
            )
        %>
        <ul class="nav hidden-old-phone">
          <li id="home_link">
            <%= link_to "Home", root_path, title: 'World Mathaba Independent News Agency', rel: 'home' %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= _("Sections") %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% @site_categories.each do |category|%>
                <li> <%= link_to category.title, category, title: category.title %> </li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown hidden-phone" data-dropdown="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= _("Regions") %> <b class="caret"></b></a>
            <ul class="dropdown-menu hidden-phone">
              <% @site_region_tags.each do |tag|%>
                <li> <%= link_to tag.title, tag_path(tag), title: tag.title %> </li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown hidden-phone hidden-tablet" data-dropdown="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= _("Countries") %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% @site_country_tags.each do |tag| %>
                <li> <%= link_to tag.title, tag_path(tag), title: tag.title %> </li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown hidden-phone hidden-tablet" data-dropdown="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= _("Tags") %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% @site_general_tags.each do |tag| %>
                <li> <%= link_to tag.title, tag_path(tag), title: tag.title %> </li>
              <% end %>
            </ul>
          </li>
          <li class="dropdown hidden-phone" data-dropdown="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Links <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <% @site_links.each do |link| %>
                <li> <%= link_to(link.title, link.url, target: 'blank', title: link.link_title, rel: link.rel) %> </li>
              <% end %>
            </ul>
          </li>
        </ul>
      <% end %>


      <div class="btn-group pull-right hidden-old-phone hidden-phone">
        
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-user"></i>
          <% if current_user %>
            <%= current_user.title %>
          <% elsif current_admin_user %>
            <%= current_admin_user.title %>
          <% else %>
            <%= _("Account") %>
          <% end %>
          <span class="caret"></span>
        </a>

        <ul class="dropdown-menu">

          <% if current_admin_user %>

            <li>
              <%= link_to edit_user_registration_url(protocol: http_protocol), title: _("Edit My Profile") do %>
                <i class="icon-user"></i>
                <%= _("Edit Profile") %>
              <% end %>
            </li>

            <li>
              <%= link_to author_path(current_admin_user), title: _("My Articles Page") do %>
                <i class="icon-list"></i>
                <%= _("My Articles") %>
              <% end %>
            </li>

            <li>
              <%= link_to subscriptions_path, title: _("My Subscriptions") do %>
                <i class="icon-envelope"></i>
                <%= _("My Subscriptions") %>
              <% end %>
            </li>
            
            <li class="divider"></li>
            
            <li>
              <%= link_to admin_dashboard_url(protocol: http_protocol) do %>
                <i class="icon-briefcase"></i>
                <%= _("Admin") %>
              <% end %>
            </li>
            <li>
              <%= link_to admin_charts_url(protocol: http_protocol) do %>
                <i class="icon-book"></i>
                <%= _("Statistics") %>
              <% end %>
            </li>

            <% if current_ability.can?(:create, Item) %>
              <li>
                <%= link_to new_admin_item_path(protocol: http_protocol) do %>
                  <i class="icon-pencil"></i>
                  <%= _("Submit Article") %>
                <% end %>
              </li>
            <% end %>

            <% if current_admin_user.has_any_role?(:admin,:security) %>
              <li class="divider"></li>
              <%= render partial: "/shared/system_menu" %>
            <% end %>

            <li class="divider"></li>

            <li>
              <%= link_to destroy_admin_user_session_url(protocol: http_protocol),
                    title: _('Logout'),
                    method: :delete do
              %>
                <i class="icon-off"></i>
                <%= _("Sign out") %>
              <% end %>
            </li>

          <% elsif current_user %>

            <li>
              <%= link_to edit_user_registration_url(protocol: http_protocol),
                  title: _("Edit My Profile") do 
              %>
                <i class="icon-user"></i>
                <%= _("Edit Profile") %>
              <% end %>
            </li>

            <% if current_ability.can?(:create, Item) %>
              <li>
                <%= link_to new_admin_item_path(protocol: http_protocol) do %>
                  <i class="icon-pencil"></i>
                  <%= _("Submit Article") %>
                <% end %>
              </li>
            <% end %>

            <li>
              <%= link_to author_path(current_user), title: _("My Articles Page") do %>
                <i class="icon-list"></i>
                <%= _("My Articles") %>
              <% end %>
            </li>

            <li>
              <%= link_to subscriptions_path, title: _("My Subscriptions") do %>
                <i class="icon-envelope"></i>
                <%= _("My Subscriptions") %>
              <% end %>
            </li>
            
            <% if current_user.has_any_role?(:admin,:security) %>
              <li class="divider"></li>
              <%= render partial: "/shared/system_menu" %>
            <% end %>
            
            <li class="divider"></li>
            
            <li>
              <%= link_to destroy_user_session_url(protocol: http_protocol),
                    method: :delete,
                    title: _('Logout') do
              %>
                <i class="icon-off"></i>
                <%= _("Sign out") %>
              <% end %>
            </li>

          <% else %>

            <li> <%= login_link _('Sign in') %> </li>
            <%- if Devise.mappings[:user].registerable?  %>
              <li>
                <%= link_to _("Sign up"), new_registration_url(:user, protocol: http_protocol), title: _("Register a new Account") %>
              </li>
            <% end -%>
            <%- if Devise.mappings[:user].recoverable? && controller_name != 'passwords' %>
              <li> <%= link_to _("Forgot password?"), new_password_url(:user, protocol: http_protocol) %> </li>
            <% end -%>
            <%- if Devise.mappings[:user].confirmable? && controller_name != 'confirmations' %>
              <li>
                <%= link_to _("Didn't receive confirmation instructions?"), new_confirmation_url(:user, protocol: http_protocol) %>
              </li>
            <% end -%>

          <% end %>

        </ul>
      </div>
    </div>
  </div>
</div>
<!-- </header> -->

app/views/shared/layouts/_sidebar.html.erb
<div class="sidebar">

  <div class="well social">
    <%= flattr_medium %>
    <%= rss_medium %>
    <%= google_plus_new %>
    <%= twitter_medium %>
    <%= facebook_medium %>
  </div>

  <% if is_handheld? %>
    <div class="well social hidden-desktop visible-tablet visible-phone">
      <% if current_user %>
        <%= link_to t("Edit Profile"),
              edit_user_registration_url(protocol: http_protocol),
              title: _("Edit My Profile"),
              class: "btn"
        %>
        <%= link_to _("My Articles"),
              author_path(current_user),
              title: _("My Articles Page"),
              class: 'btn'
        %>
      <% else %>
        <%= link_to _('Sign in'),
              new_session_url(:user, protocol: http_protocol),
              title: _('Sign in'),
              class: 'btn'
        %>
        <%- if Devise.mappings[:user].registerable?  %>
          <%= link_to _("Register"),
                new_registration_url(:user, protocol: http_protocol),
                title: _("Register a new Account"),
                class: 'btn'
          %>
        <% end -%>
      <% end %>
    </div>
  <% end %>

  <div class="well">
    <%= form_tag(search_path, method: :get, class: 'search-form') do |f| %>
      <%= text_field_tag :q, 
            params[:q], 
            type: "search", 
            class: "span3 search-query",
            placeholder: _("Search Articles"),
            autofocus: false
      %>
      <button class="btn search" type="submit"><%= _("Search") %></button>
    <% end %>

    <div class="sidebar_secions">
      <% if @search && @search.total > 0 %>
        <div class='widget'>
          <div class='widget_content'>
            <ul class="nav nav-list">
              <li class="horizontal-divider"></li>
              <li class="nav-header"><%= _("Search by Category") %></li>
              <% @search.facet(:category_id).rows.each do |facet| %>
                <% category = Category.find(facet.value) %>
                <li>
                  <%= link_to("#{category.title} (#{facet.count})", params.merge(category_id: category.id, page: nil)) if category %>
                  <%= link_to(_("Remove"), params.merge(category_id: nil), class: 'link-remove') if params[:category_id] %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <br />
      <% end %>
    </div>

    <% if account_sidebar? %>
      <div class='sidebar_secions'>
        <ul class="nav nav-list">
          <li class="horizontal-divider"></li>
          <% if current_user %>
            <li>
              <%= link_to _("Edit Profile"), edit_user_registration_url(protocol: 'https') %>
            </li>
            <li>
              <%= link_to _("My Articles"), author_path(current_user), title: "My Articles Page" %>
            </li>
            <li>
              <%= link_to _('Sign out'), destroy_user_session_url(protocol: 'https'), method: :delete %>
            </li>
          <% elsif current_admin_user %>
            <li>
              <%= link_to _("Edit Profile"), edit_user_registration_url(protocol: 'https') %>
            </li>
            <li>
              <%= link_to _("My Articles"), author_path(current_admin_user), title: _("My Articles Page") %>
            </li>
            <li>
              <%= link_to _('Sign out'), destroy_user_session_url(protocol: 'https'), method: :delete %>
            </li>
          <% else %>
            <%- if controller_name != 'sessions' %>
              <li><%= link_to _("Sign in"), new_session_url(resource_name, protocol: "https") %></li>
            <% end -%>
            <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
              <li><%= link_to _("Sign up"), new_registration_url(resource_name, protocol: "https") %></li>
            <% end -%>
            <%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
              <li>
                <%= link_to _("Forgot Password?"), new_password_url(resource_name, protocol: "https") %>
              </li>
            <% end -%>
            <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
              <li>
                <%= link_to _("Didn't receive confirmation instructions?"), new_confirmation_url(resource_name, protocol: "https") %>
              </li>
            <% end -%>
            <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
              <li>
                <%= link_to _("Didn't receive unlock?"), new_unlock_url(resource_name, protocol: 'https') %>
              </li>
            <% end -%>
            <%- if devise_mapping.omniauthable? %>
              <%- resource_class.omniauth_providers.each do |provider| %>
                <li><%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %></li>
              <% end -%>
            <% end -%>
          <% end -%>
        </ul>
      </div>
    <% end %>


    <% cache_expiring(sidebar_cache_key, 1.day) do %>
      <div class="sidebar_secions">
        <ul class="nav nav-list">
          <li class="horizontal-divider"></li>
          <% @site_categories.each do |category| %>
            <li class="<%= li_class(category.to_param, :id, 'active') %>">
              <%= link_to category.title, category, title:  category.description %>
            </li>
          <% end %>
          <li class="horizontal-divider"></li>
        </ul>
        <ul class="nav nav-list">
          <% @site_pages.each do |page| %>
            <li class="<%= li_class(page.to_param, :id, 'active') %>">
              <%= link_to page.title, page, title:  page.title %>
            </li>
          <% end %>
          <% @private_pages.each do |page| %>
            <li class="<%= li_class(page.to_param, :id, 'active') %>">
              <%= link_to page.title, page, title:  page.title %>
            </li>
          <% end %>
          <li><%= link_to "Other Sites", links_path %></li>
          <li class="horizontal-divider"></li>
        </ul>
      </div>
    <% end %>

    <% cache_expiring("sidebar_comment/#{Comment.last_cache_key}", 1.day) do %>
      <div class="sidebar_secions">
        <h4><%= _("Recently Discussed") %></h4>
        <% Item.localized.recently_commented(8).each do |item| %>
          <div class="sidebar-item">
            <%= item_mini(item).html_safe %>
            <span class="comment-date">
              <i class="icon-comments"></i>
              <%= item.comments_count %>
              <%= n_("Comment", "Comments", item.comments_count) %>
            </span>
            <span class="horizontal-divider"></span>
          </div>
        <% end %>
      </div>
    <% end %>

    <% cache_expiring("sidebar_popular", 1.day) do %>
      <div class="sidebar_secions">
        <h4><%= _("Popular this month") %></h4>
        <% Item.localized.popular(5).each do |item| %>
          <div class="sidebar-item">
            <%= item_mini(item).html_safe %>
            <span class="horizontal-divider"></span>
          </div>
        <% end %>
      </div>
    <% end %>

    <% cache_expiring("sidebar_searches", 1.day) do %>
      <div class="sidebar_secions">
        <h4><%= _("Popular Searches") %></h4>
        <% SearchQuery.popular(FastGettext.locale).limit(10).each do |query| %>
          <ul class="nav nav-list">
            <li><%= link_to query.keyword.to_s.truncate(24).gsub('"'," ").gsub('+'," "), search_path(q: query.keyword) %></li>
          </ul>
        <% end %>
        <span class="horizontal-divider"></span>
      </div>
      <div class="hidden-phone">
        <%= image_tag "adfreesite.png",
              alt: _("AdFree Site"),
              title:  _("This is an Advertisement Free Site"),
              width: 100, height: 60
        %>
      </div>
    <% end %>

  </div>
</div>