config/routes.rb
Publication::Application.routes.draw do

  require 'sidekiq/web'
  constraint = lambda { |request| request.env["warden"].authenticate? && request.env['warden'].user.is_admin? }
  constraints constraint do
    mount Sidekiq::Web => '/queue'
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, controllers: {registrations: :registrations}

  match 'opensearch' => 'items#opensearch', :as => :opensearch
  match 'benchmark_solr' => 'items#benchmark_solr', :as => :benchmark_solr
  match 'search' => 'items#search', :as => :search
  match 'feed' => "items#feed", :as => :feed
  match 'languages/:language_id/items/page/:page' => 'items#index'
  match 'categories/:category_id/:page' => 'items#index'

  match 'news/:category/:id' => 'items#show', :as => :news_path

  post '/tinymce_assets' => 'attachments#create'

  # Omniauth
  match '/auth/:provider/callback', to: 'services#create'
  match '/auth/failure' => 'services#failure'
  resources :services, :only => [:create, :destroy]

  namespace "api" do
    resources :git_push
  end

  # opinio_model
  resources :authors do
    resources :items
    resources :comments, controller: 'opinio/comments'
  end

  resources :items do
    resources :language
    resources :category
    opinio
    get 'vote'
  end

  resources :comments, controller: 'opinio/comments' do
    get 'reply', on: :member
    get 'vote'
  end

  resources :links, only: [:index]
  resources :subscriptions, only: [:index, :destroy]
  resources :contacts
  resources :pages
  resources :roles
  resources :tags
  resources :general_tags
  resources :region_tags
  resources :country_tags
  resources :categories
  resources :attachments
  resources :scores
  resources :translations
  resources :languages do
    resources :items
  end

  # Main Items feed
  match '/atom' => 'items#index', :as => :items_atom, :defaults => { :format => 'atom' }
  match '/rss'  => 'items#index', :as => :items_rss,  :defaults => { :format => 'rss' }


  namespace :tasks do
    get 'sitemap'
  end

  root to: 'categories#index'

  match '*not_found', to: 'errors#error_404'
end

app/models/category.rb
class Category < ActiveRecord::Base
  
  # Versioning System
  has_paper_trail
  
  # Validations
  validates_presence_of :title
  validates_presence_of :description
  validates_uniqueness_of :title
  
  # Relationships
  has_many :items, inverse_of: :category

  has_one :last_item,
    class_name: "Item",
    order: "items.published_at DESC",
    conditions: proc { ["(items.draft = ?) AND (published_at is not NULL) AND (published_at < ?)", false, Time.now.to_s(:db)] }
  
  # Permalink URLS
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  def published_items
    self.
      items.
      not_draft.
      published.
      order("published_at DESC")
  end
  
  def top_items(lmt=8)
    self.
      items.
      reduced.
      not_draft.
      localized.
      published.
      order("published_at DESC").
      limit(lmt)
  end

  def item_last_update
    t = self.last_item
    if t
      t.updated_at
    else
      Time.now
    end
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :check_params_encoding, only: [:show]
  before_filter :last_modified, only: [:index]

  def index
    @sticky_item = Item.top_sticky
    if @sticky_item
      @highlights = [@sticky_item]
      @latest_items = Item.highlights(3)
    else
      @top_items = Item.highlights(4)
      @highlights = [@top_items.first]
      @latest_items = @top_items[1..3]
    end
    @categories = @site_categories
    no_cache_headers
  end

  def show
    @show_breadcrumb = true
    @category = Category.find(params[:id])
    @items = @category.
      items.
      not_draft.
      localized.
      published.
      order("published_at DESC").
      page(params[:page]).per(per_page)

    # RSS configuration
    @rss_title = "World Mathaba - #{@category.title} News"
    @meta_title = @rss_title
    @rss_description = "#{@category.description} News"
    @meta_description = @rss_description
    @rss_source = url_for(@category)
    @rss_category = @category.title
    @rss_language = "en"
    @meta_keywords = "#{@category.title} news"

    if @items.empty?
      @etag = Digest::MD5.hexdigest((Time.now.to_i / 900).to_s)
    else
      @last_published = @items.first.published_at
      @etag = Digest::MD5.hexdigest(@items.map{|t| t.id}.to_s)
    end

    respond_to do |format|
      format.html {
        fresh_when(etag: @etag, last_modified: @last_published) unless (current_user or current_admin_user)
      }
      format.atom {
        headers['Etag'] = @etag
        public_headers(900)
        render partial: "/shared/items", layout: false 
      }
      format.rss {
        headers['Etag'] = @etag
        public_headers(900)
        render partial: "/shared/items", layout: false
      }
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:rss,  items_rss_path,  format: "rss") %>
  <%= auto_discovery_link_tag(:atom, items_atom_path, format: "atom") %>
<% end %>

<div class="row categories">

  <div class="span6 box" id="main_highlights">
    <% if @highlights && @highlights.first %>
      <% cache_expiring("main/#{@highlights.first.cache_key}", 8.hour) do %>
        <ul>
          <% @highlights.each do |item| %>
            <li class="featured_item" id="highlight_item_<%=item.id%>">
              <% if item.has_image? %>
                <%= link_to(
                      image_tag(item.main_image.image.main,
                        class: "featured_item_image",
                        alt: item.main_image.title,
                        width: 300, height: 300
                      ),
                      item,
                      title: item.abstract,
                      class: 'easy-tooltip'
                    )
                %>
              <% elsif item.youtube_id && item.youtube_img %>
                <%= link_to(
                      image_tag("https://img.youtube.com/vi/#{item.youtube_id}/0.jpg",
                        class: "youtube_main",
                        alt: item.youtube_id
                      ),
                      item,
                      title: item.abstract,
                      class: 'easy-tooltip'
                    )
                %>
              <% end %>
              <span class="title">
                <%= link_to item.title.to_s.truncate(100),
                            item,
                            title: item.abstract,
                            class: 'easy-tooltip'
                %>
              </span>
              <span class="abstract"><%= item.abstract.to_s.truncate(120) %></span>
            <% end %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
  
  <div class="span6 box" id="highlights">
    <% if @latest_items && @latest_items.first %>
      <% cache_expiring("hglt/#{@latest_items.map{|t| t.updated_at.to_f}.sum}", 1.hour) do %>
        <h2><%= link_to _("Latest News"), items_path, title: _("Latest News") %></h2>
        <ul>
        <% @latest_items.each do |item| %>
          <li class="list_item" id="highlight_item_<%=item.id%>">
            <% if item.has_image? %>
              <%= link_to(
                    image_tag(item.main_image.image.small,
                        class: "list_item_image",
                        alt: item.main_image.title,
                        width: 100, height: 100
                    ),
                    item,
                    title: item.abstract,
                    class: 'easy-tooltip'
                  )
              %>
            <% elsif item.youtube_id && item.youtube_img %>
              <%= image_tag("https://img.youtube.com/vi/#{item.youtube_id}/2.jpg",
                    class: "list_item_image youtube_small", alt: item.youtube_id
                  )
              %>
            <% end %>
            <span class="title">
              <%= link_to item.title.to_s.truncate(120),
                          item,
                          title: item.abstract,
                          class: 'easy-tooltip'
              %>
            </span>
            <span class="abstract">
              <%= item.abstract.to_s.truncate(120) %>
            </span>
          </li>
        <% end %>
        </ul>
        <span class="more breaking-news">
          <%= link_to _("more..."), items_path, title: _("Read more breaking news"), class: 'easy-tooltip' %>
        </span>
      <% end %>
    <% end %>
  </div>

  <% for category in @categories %>
    <% @top_items = category.top_items(12) %>
    <% unless @top_items.empty? %>
      <% cache_expiring("box/#{category.id}/#{@top_items.map{|t| t.updated_at.to_f}.sum}", 8.hours) do %>
        <div class="span6 box" id="<%= category.slug %>">
          <h2><%= link_to category.title, category, title: _("Read more articles in this category") %></h2>
          <ul>
            <% @top_items.each_with_index do |item,index|%>
              <li class="list_item" id="item_<%=item.id%>">
                <% if index==0 %>
                  <% if item.has_image? %>
                    <%= link_to(
                          image_tag(item.main_image.image.small,
                            class: "list_item_image", 
                            alt: item.main_image.title,
                            width: 100, height: 100
                          ),
                          item, 
                          title: item_title_small(item),
                          class: 'easy-tooltip'
                        )
                    %>
                  <% elsif item.youtube_id && item.youtube_img %>
                    <%= image_tag("https://img.youtube.com/vi/#{item.youtube_id}/0.jpg", 
                          class: "list_item_image youtube_small",
                          alt: item.youtube_id
                        )
                    %>
                  <% end %>
                  <%= link_to item.title.to_s.truncate(100), item, 
                          title: item_title_small(item), class: 'easy-tooltip'
                  %>
                  <span class="abstract"><%= item.abstract.to_s.truncate(120) %></span>
                <% else %>
                  <span class="noroll">
                    <%= link_to item.title.to_s.truncate(100), item,
                          title: item_title(item), class: 'easy-tooltip'
                    %>
                  </span>
                <% end %>
              </li>
            <% end %>
          </ul>
          <span class="more">
            <%= link_to _("more..."), category, title: _("Read more articles in this category") %>
          </span>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:rss, action: 'show', id: @category.id, format: "rss") %>
  <%= auto_discovery_link_tag(:atom, action: 'show', id: @category.id, format: "atom") %>
<% end %>


<% @items.each do |item| %>
  <%= render partial: "/shared/item", locals: {item: item } %>
<% end %>

<% content_for :breadcrumb do %>

  <li>
    <%= link_to "Home", root_path, title: "Home", rel: 'home' %>
    <span class="divider">/</span>
  </li>
  
  <li class="active">
    <h1>
      <%= @category.title %>
      <%= link_to(
            image_tag("icons/social/rss_16.png", alt: "RSS for #{@category.title}"), 
            category_path(@category, format: "rss"),
            title: (_("RSS feed for items in category %{str}") % { str: @category.title })
          )
      %>
    </h1>
  </li>
  
<% end %>

<div class="pagination">
  <%= paginate @items %>
</div>